# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='cookbooks',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='Cookbooks',
        ),
    ]
