# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='not available', max_length=128),
        ),
    ]
