# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('recipes', '0004_auto_20160110_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ManyToManyField(related_name='recipes', to='authors.Author'),
        ),
    ]
